UPDATE PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 0.9 WHERE EMBALAGEM = 'Lata';

UPDATE PRODUTOS SET EMBALAGEM = 'Garrafa', PRECO_LISTA = 8.10 WHERE CODIGO_PRODUTO = '1088126';

DELETE FROM PRODUTOS WHERE CODIGO_PRODUTO = '1004327';