SELECT * FROM CLIENTES;

SELECT * FROM VENDEDORES v ORDER BY NOME;

SELECT c.NOME_COMPLETO as [Nome do cliente], c.CPF, c.ESTADO as UF from CLIENTES c order by NOME_COMPLETO;

--Desafio: quem são as pessoas vendedoras?

SELECT MATRICULA AS IDENTIFICADOR, NOME AS [NOME DO VENDEDOR] FROM VENDEDORES;

SELECT DISTINCT SABOR FROM PRODUTOS;

SELECT c.NOME_COMPLETO, c.ESTADO FROM CLIENTES c WHERE c.PRIMEIRA_COMPRA = 1; 

--

SELECT NOME_COMPLETO, BAIRRO FROM CLIENTES WHERE BAIRRO = 'Copacabana' or BAIRRO = 'Tijuca';

--Desafio: informações específicas

SELECT * FROM VENDEDORES WHERE PERCENTUAL_COMISSAO <= 0.08;

SELECT * FROM PRODUTOS WHERE PRECO_LISTA <= 6.00; 

SELECT * FROM CLIENTES WHERE ESTADO <> 'SP' AND ESTADO <> 'RJ';