CREATE DATABASE SUCOS_VENDAS;

CREATE TABLE [CLIENTES] (
	[CPF] [CHAR] (11),
	[NOME_COMPLETO] [VARCHAR] (150),
	[RUA] [VARCHAR] (150),
	[COMPLEMENTO] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (150),
	[ESTADO] [CHAR] (2),
	[CEP] [CHAR] (8),
	[DATA_NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[SEXO] [CHAR] (1),
	[LIMITE_CREDITO] [MONEY],
	[VOLUME_MININO] [FLOAT],
	[PRIMEIRA_COMPRA] [BIT]
);

CREATE TABLE [PRODUTOS] (
	[CODIGO_PRODUTO] [VARCHAR] (20) NOT NULL PRIMARY KEY,
	[NOME_PRODUTO] [VARCHAR] (50),
	[EMBALAGEM] [VARCHAR] (50),
	[TAMANHO] [VARCHAR] (50),
	[SABOR] [VARCHAR] (50),
	[PRECO_LISTA] [SMALLMONEY]
);

ALTER TABLE CLIENTES ALTER COLUMN [CPF] [CHAR] (11) NOT NULL;
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY CLUSTERED ([CPF]);


--Desafio: tabela vendedores
CREATE TABLE [VENDEDORES] (
	[MATRICULA] [CHAR] (5),
	[NOME] [VARCHAR] (100),
	[PERCENTUAL_COMISSAO] [FLOAT]
);

ALTER TABLE VENDEDORES ALTER COLUMN [MATRICULA] [CHAR] (5) NOT NULL;
ALTER TABLE VENDEDORES ADD CONSTRAINT PK_VENDEDORES PRIMARY KEY CLUSTERED ([MATRICULA]);

